FROM nginx:1.10.1-alpine
COPY src/html /user/share/nginx/html

## Documentation
# EXPOSE 80

# CMD [ "nginx", "-g", "daemon off;" ]


# git clone https://<username>:<githubtoken>@github.com/<username>/<repositoryname>.git